# 基础花费
base: 100.0

# 花费修饰
modifiers:

  # 物品损耗
  damage:
    operation: "add_value"
    expression: "1.0 * query.value"

  # 物品稀有度
  rarity:
    operation: "add_value"
    expression: "1.0 * query.value"
    mapping:
      common: 0.0
      uncommon: 1.0
      rare: 2.0
      epic: 3.0
      legendary: 4.0
      ancient: 5.0
