# 该图标对应合成站中主列表里的一个特定的配方的结果.
# 该图标基于配方的结果本身的信息生成, 因此不需要 base.

slot_display_name: "合成: <item_name>"

# 额外占位符
# {choice_list}
slot_display_lore:
  - "<!i><color:#afded6><st>                    </color>"
  - "<!i><color:#ffba4a>所需材料</color><gray>:</gray>"
  - "{choice_list}"
  - "<!i><color:#afded6><st>                    </color>"
  - "<!i><color:#fdff87>预览配方</color><dark_gray>:</dark_gray> <color:#7dffb5>左键单击</color>"
  - "<!i><color:#fdff87>合成一次</color><dark_gray>:</dark_gray> <color:#7dffb5>右键单击</color>"
  - "<!i><color:#fdff87>合成八次</color><dark_gray>:</dark_gray> <color:#7dffb5>潜行单击</color>"
  - "<!i><color:#fdff87>合成全部</color><dark_gray>:</dark_gray> <color:#7dffb5><key:key.drop>键丢出</color>"
  - "<!i><color:#afded6><st>                    </color>"

slot_display_dict:
  ok: "<green>✔</green>"
  bad: "<red>✘</red>"
  # 额外占位符
  # <requirement_mark>
  # <item>
  # <amount>
  choice_item: "<!i><white><requirement_mark> <item> <gray>×</gray> <amount>"
  # 额外占位符
  # <requirement_mark>
  # <amount>
  choice_exp: "<!i><white><requirement_mark> 经验值 <gray>×</gray> <amount>"
