# 不要修改!
version: 1

display:
  triggers:
    generic/left_click: "<green><b>L"
    generic/right_click: "<green><b>R"

  player_combo:
    connector: "<gray>-"
    success_message:
      - type: actionbar
        text: "成功! <trigger_completed>"

    failure_message:
      - type: actionbar
        text: "失败. <trigger_completed>"

    progress_message:
      - type: actionbar
        text: "<trigger_completed>"

    mana_cost_message:
      - type: actionbar
        text: "<aqua><gray>-</gray> <aqua><count></aqua> <blue>[</blue>●<blue>]</blue></aqua>"

    no_enough_mana_message:
      - type: chat
        text: "<red>没魔了. </red>"
