# 元素

# 所有的元素
elements:

  # 排在首位的元素将成为默认元素
  neutral:
    binary_index: 0
    display_name: 中立
    styles: "<white>"

  fire:
    binary_index: 1
    display_name: 火
    styles: "<white>"

  water:
    binary_index: 2
    display_name: 水
    styles: "<white>"

  wind:
    binary_index: 3
    display_name: 风
    styles: "<white>"

  earth:
    binary_index: 4
    display_name: 土
    styles: "<white>"

  thunder:
    binary_index: 5
    display_name: 雷
    styles: "<white>"
