# 该文件定义了所有的元素

# FIXME 移除 binary_index, 持久化直接储存 id

# 每个元素的具体定义
elements:

  # 默认元素
  # 当游戏尝试寻找一个元素但不存在时将使用该元素
  # id 为 "neutral" 的元素将自动作为默认元素
  #
  # 默认元素有如下特殊要求:
  # - 禁止修改这里的节点 `binary_index`
  # - 禁止修改这里的字段 "neutral"
  neutral:
    binary_index: 0
    display_name: 中立
    styles: "<white>"

  fire:
    binary_index: 1
    display_name: 火
    styles: "<white>"

  water:
    binary_index: 2
    display_name: 水
    styles: "<white>"

  wind:
    binary_index: 3
    display_name: 风
    styles: "<white>"

  earth:
    binary_index: 4
    display_name: 土
    styles: "<white>"

  thunder:
    binary_index: 5
    display_name: 雷
    styles: "<white>"
