# 不要修改!
version: 1

# 实体的默认属性
#
# 你必须在这里定义每种实体所拥有的属性及其数值
# 如果一个实体没有定义属性 X, 则该实体没有属性 X
#
# 例外:
# 如果一个属性 X 它是基于原版属性, 并且
# - 在这里没有节点, 那么最终将返回 X 所对应原版属性的数值, 而非没有属性 X
# - 在这里存在节点, 那么最终将返回这里 X 指定的值, 或 X 的全局默认值, 如果值为空
entity_attributes:

  # 这是一个例子, 用来说明配置的格式
  #
  # 这里指定实体的 id, 必须是命名空间格式
  # 这里的 id 不一定要来自游戏内, 可以按需编造, 例如这里的 "koish:example"
  # 但如果要为游戏内的某个实体类型指定默认属性, 该 id 必须能够匹配一个实际存在的实体 id
  koish:example/1:
    # 父属性配置的 key, 必须出现在该属性配置之前. 可为空
    parent: ~
    # 在 values 下指定该实体的默认属性及其数值
    values:
      # 如果一个属性带元素, 并且不是 map 结构, 则相当于给该属性的每个元素都指定了一个值
      # 例如这里的 defense 属性, 它是一个元素属性, 所以相当于指定每个元素都使用默认值
      defense: default # default 意为自动采用属性的全局默认值
      # 如果一个属性带元素, 并且是 map 结构, 则可以单独给某个元素指定一个值
      # 如果这里缺失了某个元素类型, 则缺失元素对应的属性将采用全局属性默认值
      attack_damage_rate:
        neutral: 1.0
        thunder: 0.5
      # 如果一个属性不带元素, 则直接写标量来指定其数值
      max_mana: 100.0
      # 对于那些由两个数值组成的属性, 例如 attack_damage (min 和 max),
      # 永远是(也只能)同时指定 min 和 max, 无法单独指定其 min 和 max.
      # 也就是说, 写法上这些属性与只有一个数值的属性没有任何区别.
      attack_damage: 5.0

  # 这是一个例子, 用来说明配置的格式
  #
  # 这个例子说明了继承的基本概念和用法
  koish:example/2:
    parent: koish:example/1
    values:
      attack_effect_chance: default
      # 这里的 defense 属性虽然被注释了, 但 koish:example/2 依然拥有 defense 属性!
      # 这是因为其继承了 koish:example/1, 而 koish:example/1 拥有 defense 属性
      # defense: default

  minecraft:living:
    parent: ~
    values:
      defense: 0
      incoming_damage_rate: 1.0
      blocking_damage_reduction: 0
      universal_defense: 0

  minecraft:player:
    parent: ~
    values:
      attack_damage: default
      attack_damage_rate: default
      attack_effect_chance: default
      attack_knockback: default
      block_interaction_range: default
      blocking_damage_reduction: default
      critical_strike_chance: default
      critical_strike_power: default
      defense_penetration: default
      defense_penetration_rate: default
      entity_interaction_range: default
      hammer_damage_range: default
      hammer_damage_ratio: default
      health_regeneration: default
      incoming_damage_rate: default
      knockback_resistance: default
      lifesteal: default
      manasteal: default
      mana_consumption_rate: default
      mana_regeneration: default
      max_absorption: default
      max_health: default
      max_mana: 200.0
      movement_speed: default
      negative_critical_strike_power: default
      none_critical_strike_power: default
      sweeping_damage_ratio: default
      universal_attack_damage: default
      universal_defense: default
      universal_defense_penetration: default
      universal_defense_penetration_rate: default
      water_movement_efficiency: default

  minecraft:allay:
    parent: minecraft:living
    values: { }

  minecraft:armadillo:
    parent: minecraft:living
    values: { }

  minecraft:armor_stand:
    parent: minecraft:living
    values: { }

  minecraft:axolotl:
    parent: minecraft:living
    values: { }

  minecraft:bat:
    parent: minecraft:living
    values: { }

  minecraft:bee:
    parent: minecraft:living
    values: { }

  minecraft:blaze:
    parent: minecraft:living
    values: { }

  minecraft:bogged:
    parent: minecraft:living
    values: { }

  minecraft:breeze:
    parent: minecraft:living
    values: { }

  minecraft:camel:
    parent: minecraft:living
    values: { }

  minecraft:cat:
    parent: minecraft:living
    values: { }

  minecraft:cave_spider:
    parent: minecraft:living
    values: { }

  minecraft:chicken:
    parent: minecraft:living
    values: { }

  minecraft:cod:
    parent: minecraft:living
    values: { }

  minecraft:cow:
    parent: minecraft:living
    values: { }

  minecraft:creeper:
    parent: minecraft:living
    values: { }

  minecraft:dolphin:
    parent: minecraft:living
    values: { }

  minecraft:donkey:
    parent: minecraft:living
    values: { }

  minecraft:drowned:
    parent: minecraft:living
    values: { }

  minecraft:elder_guardian:
    parent: minecraft:living
    values: { }

  minecraft:ender_dragon:
    parent: minecraft:living
    values: { }

  minecraft:enderman:
    parent: minecraft:living
    values: { }

  minecraft:endermite:
    parent: minecraft:living
    values: { }

  minecraft:evoker:
    parent: minecraft:living
    values: { }

  minecraft:fox:
    parent: minecraft:living
    values: { }

  minecraft:frog:
    parent: minecraft:living
    values: { }

  minecraft:ghast:
    parent: minecraft:living
    values: { }

  minecraft:giant:
    parent: minecraft:living
    values: { }

  minecraft:glow_squid:
    parent: minecraft:living
    values: { }

  minecraft:goat:
    parent: minecraft:living
    values: { }

  minecraft:guardian:
    parent: minecraft:living
    values: { }

  minecraft:happy_ghast:
    parent: minecraft:damageable
    values: { }

  minecraft:hoglin:
    parent: minecraft:living
    values: { }

  minecraft:horse:
    parent: minecraft:living
    values: { }

  minecraft:husk:
    parent: minecraft:living
    values: { }

  minecraft:illusioner:
    parent: minecraft:living
    values: { }

  minecraft:iron_golem:
    parent: minecraft:living
    values: { }

  minecraft:llama:
    parent: minecraft:living
    values: { }

  minecraft:magma_cube:
    parent: minecraft:living
    values: { }

  minecraft:mooshroom:
    parent: minecraft:living
    values: { }

  minecraft:mule:
    parent: minecraft:living
    values: { }

  minecraft:ocelot:
    parent: minecraft:living
    values: { }

  minecraft:panda:
    parent: minecraft:living
    values: { }

  minecraft:parrot:
    parent: minecraft:living
    values: { }

  minecraft:phantom:
    parent: minecraft:living
    values: { }

  minecraft:pig:
    parent: minecraft:living
    values: { }

  minecraft:piglin:
    parent: minecraft:living
    values: { }

  minecraft:piglin_brute:
    parent: minecraft:living
    values: { }

  minecraft:pillager:
    parent: minecraft:living
    values: { }

  minecraft:polar_bear:
    parent: minecraft:living
    values: { }

  minecraft:pufferfish:
    parent: minecraft:living
    values: { }

  minecraft:rabbit:
    parent: minecraft:living
    values: { }

  minecraft:ravager:
    parent: minecraft:living
    values: { }

  minecraft:salmon:
    parent: minecraft:living
    values: { }

  minecraft:sheep:
    parent: minecraft:living
    values: { }

  minecraft:shulker:
    parent: minecraft:living
    values: { }

  minecraft:skeleton:
    parent: minecraft:living
    values: { }

  minecraft:skeleton_horse:
    parent: minecraft:living
    values: { }

  minecraft:slime:
    parent: minecraft:living
    values: { }

  minecraft:sliverfish:
    parent: minecraft:living
    values: { }

  minecraft:sniffer:
    parent: minecraft:living
    values: { }

  minecraft:snow_golem:
    parent: minecraft:living
    values: { }

  minecraft:spider:
    parent: minecraft:living
    values: { }

  minecraft:squid:
    parent: minecraft:living
    values: { }

  minecraft:stray:
    parent: minecraft:living
    values: { }

  minecraft:strider:
    parent: minecraft:living
    values: { }

  minecraft:tadpole:
    parent: minecraft:living
    values: { }

  minecraft:trader_llama:
    parent: minecraft:living
    values: { }

  minecraft:tropical_fish:
    parent: minecraft:living
    values: { }

  minecraft:turtle:
    parent: minecraft:living
    values: { }

  minecraft:vex:
    parent: minecraft:living
    values: { }

  minecraft:villager:
    parent: minecraft:living
    values: { }

  minecraft:vindicator:
    parent: minecraft:living
    values: { }

  minecraft:wandering_trader:
    parent: minecraft:living
    values: { }

  minecraft:warden:
    parent: minecraft:living
    values: { }

  minecraft:witch:
    parent: minecraft:living
    values: { }

  minecraft:wither:
    parent: minecraft:living
    values: { }

  minecraft:wither_skeleton:
    parent: minecraft:living
    values: { }

  minecraft:wolf:
    parent: minecraft:living
    values: { }

  minecraft:zoglin:
    parent: minecraft:living
    values: { }

  minecraft:zombie:
    parent: minecraft:living
    values: { }

  minecraft:zombie_horse:
    parent: minecraft:living
    values: { }

  minecraft:zombie_villager:
    parent: minecraft:living
    values: { }

  minecraft:zombified_piglin:
    parent: minecraft:living
    values: { }

  minecraft:all_zeros:
    parent: ~
    values:
      attack_damage: 0
      attack_damage_rate: 0
      critical_strike_chance: 0
      critical_strike_power: 0
      defense_penetration: 0
      defense_penetration_rate: 0
      universal_attack_damage: 0
      universal_defense_penetration: 0
      universal_defense_penetration_rate: 0

  minecraft:arrow:
    parent: minecraft:all_zeros
    values: { }

# 实体索引表 (目前仅用于条件判断)
entity_type_holders:

  # 原版怪物 minecraft:{value} (必须小写); 可用值参考 https://jd.papermc.io/paper/1.21.4/org/bukkit/entity/EntityType.html
  # MM 怪物 mythicmobs:{value} (必须小写)

  demo_bosses_1: # 索引的 id
    - minecraft:ender_dragon
    - minecraft:wither

  demo_bosses_2:
    - mythicmobs:soul_knight
    - mythicmobs:nature_golem
