# 不要修改!
version: 1

# 物品组件 (不包含物品模板)
components:

  # 这是一个示例, 用来说明配置, 在游戏内无实际作用
  __example__:
    # 是否启用该物品组件 (暂无实际作用)
    enabled: true
    # 物品组件的展示名字
    display_name: "<color:#aa2213>Example"

  brew_recipe:
    enabled: true
    display_name: "<!i><color:white>酒酿配方"

  bypass_network_rewrite:
    enabled: false
    display_name: "<!i><color:white>绕过网络重写"

  core:
    enabled: true
    display_name: "<!i><color:white>核心"

  cores:
    enabled: true
    display_name: "<!i><color:white>词条栏"

  crate:
    enabled: true
    display_name: "<!i><color:white>战利品箱"

  element:
    enabled: true
    display_name: "<!i><color:white>元素"

  id:
    enabled: true
    display_name: "<!i><color:white>标识符"

  kizami:
    enabled: true
    display_name: "<!i><color:white>刻印"

  level:
    enabled: true
    display_name: "<!i><color:white>等级"

  processed:
    enabled: false
    display_name: "<!i><color:white>已处理"

  rarity:
    enabled: true
    display_name: "<!i><color:white>稀有度"

  reforge_history:
    enabled: true
    display_name: "<!i><color:white>重铸记录"

  variant:
    enabled: true
    display_name: "<!i><color:white>变种"

  version:
    enabled: false
    display_name: "<!i><color:white>版本"
