__default__:
  tier_1:
    level: "[0,20)"
    weight:
      common: 10.0
      uncommon: 5.0
      rare: 4.0
      epic: 3.0
      ancient: 2.0
  tier_2:
    level: "[20,40)"
    weight:
      common: 8
      uncommon: 6
      rare: 5
      epic: 4
      ancient: 3
  tier_3:
    level: "[40,60)"
    weight:
      common: 6
      uncommon: 7
      rare: 6
      epic: 5
      ancient: 4
  tier_4:
    level: "[60,80)"
    weight:
      common: 4
      uncommon: 8
      rare: 7
      epic: 6
      ancient: 5
  tier_5:
    level: "[80,)"
    weight:
      common: 2
      uncommon: 9
      rare: 8
      epic: 7
      ancient: 6
