# 稀有度
rarities:

  # 该 node 是默认的稀有度, 不可删除
  # 该 node key 必须为 “common”, 否则 Koish 将强制关服
  common:

    # FIXME 移除, 持久化直接储存字符串 id 而非数字 id
    # 该稀有度的数字 id, 一旦创建好世界不要再修改
    binary_index: 0

    # 该稀有度的展示名字
    display_name: 普通

    # 该稀有度的风格样式
    # 注意, 该风格样式跟上面的 display_name 没有关系
    # 该风格样式将应用于诸如物品名字之类的文本上, 例如让具有普通稀有度的物品名字为白色, 而稀有的为青色
    styles: "<white>"

    # 该稀有度的发光颜色
    glow_color: WHITE

  # 其余的 node 为自行创建的稀有度 ...
  uncommon:
    binary_index: 1
    display_name: 罕见
    styles: "<green>"
    glow_color: GREEN

  rare:
    binary_index: 2
    display_name: 稀有
    styles: "<aqua>"
    glow_color: AQUA

  epic:
    binary_index: 3
    display_name: 史诗
    styles: "<dark_purple>"
    glow_color: DARK_PURPLE

  ancient:
    binary_index: 4
    display_name: 上古
    styles: "<gold>"
    glow_color: GOLD
