displays:
  name: "二段跳"
  tooltips:
    - "<red>二段跳"

# 技能模板的 type
type: extra_jump

# 跳跃次数
count: 2

jumped_messages:
  - type: sound
    name: "entity.player.swim"
    source: "master"
    emitter: self
