# id: <有效的属性 id>
cells/attributes/in:
  namespace: attribute
  ordinal:
    element:
      - neutral
      - fire
      - water
      - wind
      - earth
      - thunder
    operation:
      - add
      - multiply_base
      - multiply_total

# id: <有效的属性 id>
cells/attributes/out:
  namespace: attribute
  ordinal:
    element:
      - neutral
      - fire
      - water
      - wind
      - earth
      - thunder
    operation:
      - add
      - multiply_base
      - multiply_total

# id: <有效的技能 id, 如果带命名空间, 则把冒号换成 '/'>
cells/abilities/in:
  namespace: ability

# id: <有效的技能 id, 如果带命名空间, 则把冒号换成 '/'>
cells/abilities/out:
  namespace: ability

# id: `cells/empty`
cells/empty/in:
  namespace: stash
  tooltip: "[ 空核孔 ]"

# id: `cells/empty`
cells/empty/out:
  namespace: stash
  tooltip: "[ 空核孔 ]"

# id: `custom_name`
custom_name:
  namespace: vanilla
  tooltip: "定制名: <value>"

# id: `elements`
elements:
  namespace: general
  tooltip:
    merged: "元素: <merged>"
    single: "<single>"
    separator: ", "

# id: `item_name`
item_name:
  namespace: vanilla
  tooltip: "物品名: <value>"

# id: `level`
level:
  namespace: general
  tooltip: "等级: <value>"

# id: `rarity`
rarity:
  namespace: general
  simple: "稀有度: <rarity_display_name>"
  complex: "稀有度: <rarity_display_name> [<reforge_mod_count>]"

# id: `reforge_cost`
reforge_cost:
  namespace: reforge

# id: `replace_input`
replace_input:
  namespace: reforge
