# id: `custom_name`
custom_name:
  namespace: vanilla
  tooltip: "定制名: <value>"

# id: `elements`
elements:
  namespace: general
  tooltip:
    merged: "元素: <merged>"
    single: "<single>"
    separator: ", "

# id: `item_name`
item_name:
  namespace: vanilla
  tooltip: "物品名: <value>"

# id: `level`
level:
  namespace: general
  tooltip: "等级: <value>"

# id: `merge_input`
merge_input:
  namespace: reforge

# id: `merge_output`
merge_output:
  namespace: reforge
  attribute_format:
    style: "<!i><white>"
    pattern: "[+-]?\\d+(\\.\\d+)?%?(\\*+)?"
    replacement: "???"

# id: `rarity`
rarity:
  namespace: general
  simple: "稀有度: <rarity_display_name>"
  complex: "稀有度: <rarity_display_name> [<reforge_mod_count>]"
