base: paper
# 支持的占位符 (在 name 和 lore 里均有效):
# <cooking_time>
# <exp>
icon:
  name: "<!i><gold>烧炼耗时:</gold> <white><cooking_time></white> <gold>秒</gold>"
  lore:
    - "<!i><gold>烧炼经验:</gold> <white><exp></white>"