base: writable_book
slot_display_name: "RECYCLE_WHEN_CONFIRMED"
slot_display_lore:
  - "{item_list}"
  - "<total_worth>"
slot_display_dict:
  with_level: "<item_name> <item_level>"
  without_level: "<item_name>"
