# 不要修改!
version: 1

# id: `attack_speed`
attack_speed:
  namespace: topmost
  tooltip:
    line: "攻击速度: <value>"
    level:
      0: "非常慢"
      1: "慢"
      2: "普通"
      3: "快"
      4: "非常快"

# id: `cells`
cells:
  namespace: general
  tooltip: "核孔数量: <min> - <max>"

# id: `crate`
crate:
  namespace: special
  tooltip: "盲盒: <name>(<id>)"

# id: `custom_name`
custom_name:
  namespace: vanilla
  tooltip: "定制名: <value>"

# id: `elements`
elements:
  namespace: general
  tooltip:
    merged: "可能的元素(<count>): <merged>"
    single: "<single>"
    separator: ", "

# id: `enchantments`
enchantments:
  namespace: vanilla
  tooltip: "<name> <level>"

# id: `damage_resistant`
damage_resistant:
  namespace: vanilla
  tooltip: "伤害免疫"

# id: `food`
food:
  namespace: vanilla
  tooltip:
    - "饥饿值: <nutrition>"
    - "饱和度: <saturation>"
    - "食用时间: <eat_seconds>"

# id: `item_name`
item_name:
  namespace: vanilla
  tooltip: "<value>"

# id: `kizamiz`
kizamiz:
  namespace: general
  tooltip:
    merged: "可能的铭刻(<count>): <merged>"
    single: "<single>"
    separator: ", "

# id: `lore`
lore:
  namespace: general
  tooltip:
    line: "<line>"
    header: [ ]
    bottom: [ ]

# id: `portable_core`
portable_core:
  namespace: special
