# 不要修改!
version: 1

primary:
  - topmost:attack_speed

  - (fixed:general)<st><dark_gray>             </dark_gray></st>
  - general:core_container
  - general:element
  - general:kizami

  - (fixed:special)<st><dark_gray>             </dark_gray></st>
  - special:crate
  - special:core

  - (fixed:enchantments)<st><dark_gray>             </dark_gray></st>
  - enchantments:enchantments

  - (fixed:vanilla)<st><dark_gray>             </dark_gray></st>
  - vanilla:damage_resistant
  - vanilla:food

  - (fixed:general)<st><dark_gray>             </dark_gray></st>
  - general:lore
