# 技能模板的 type
blink:
  # 冲刺距离
  distance: 20

  teleported_messages:
    - type: sound
      name: "entity.player.teleport"
      source: "master"
      emitter: self

# 技能模板的 type
multi_jump:
  # 跳跃次数
  count: 2

  jumped_messages:
    - type: sound
      name: "entity.player.swim"
      source: "master"
      emitter: self