# 这是一个合成站配方的示例
#
# 该文件名为 "raw_bronze", 意思是其路径为 "raw_bronze"
# 该文件位于文件夹 "example_1" 下, 意思是位于命名空间 "example_1" 下
# 命名空间+路径共同组成了该配方的 id: "example_1:raw_bronze"
#
# 不同命名空间下的配方文件名可以重复

# 配方的输入
# 这里的 node value 为一个 list, list 中的每一个 node value 为一个 map
# map 中必须存在一个形如 "type: <id>" 的 node, 用于指定配方输入的类型
# 其他 node 根据类型的不同也将不同, 下面将作详细说明
#
# type: item
# id: <物品 id>
#   格式: "namespace:id"
#   其中 namespace 支持:
#     wakame: Koish 物品
#     minecraft: Minecraft 物品
#   其中 id 取决于具体实现
# amount: <物品堆叠数量>
#   物品堆叠的数量, 可以超过单个堆叠的最大数量
#
# type: exp
# amount: <经验值数量>
input:
  - { type: item, id: minecraft:raw_copper, amount: 3 }
  - { type: item, id: wakame:example/raw_tin, amount: 1 }
  - { type: exp, amount: 1 }

# 配方的输出
output:
  # 该物品格式为 "namespace:id", 同配方输入的写法
  item: wakame:example/bronze_ingot
  # 物品堆叠的数量, 可以超过单个堆叠的最大数量
  amount: 4