# 该类别的图标
icon: "internal/menu/catalog/default/category/test"

# 在物品图鉴主菜单中查看该类别所需的权限
# 移除该节点则无需权限
permission: "koish.catalog.item"

# 该类别的菜单布局
menu_settings:

  title: "❊ 测试"

  # .: background
  # <: prev_page
  # >: next_page
  # b: back
  # x: item
  structure:
    - ". . . . . . . . ."
    - ". x x x x x x x ."
    - ". x x x x x x x ."
    - ". x x x x x x x ."
    - ". x x x x x x x ."
    - "< . . . b . . . >"

  icons:
    background: "internal/menu/common/default/background"
    prev_page: "internal/menu/catalog/default/prev_page"
    next_page: "internal/menu/catalog/default/next_page"
    back: "internal/menu/common/default/back"

items:
  - minecraft:cake
  - minecraft:cooked_beef
  - minecraft:iron_ingot
  - minecraft:netherite_upgrade_smithing_template
  - minecraft:ward_armor_trim_smithing_template
  - minecraft:silence_armor_trim_smithing_template
  - minecraft:light_gray_dye
  - minecraft:diorite_stairs
  - minecraft:polished_diorite_stairs