# class: CatalogItemCategory

# 图鉴类别的图标
icon: "internal/menu/catalog/default/category/example"

# 图鉴类别的权限
# 如果该配置节点存在, 则玩家必须拥有权限才可以查看该类别
# 移除该配置节点则无需权限就可以查看
permission: "koish.catalog.item.example"

# 图鉴类别内容的排列方向
content_marker: VERTICAL

# 图鉴类别的物品列表
items:
  - minecraft:cake
  - minecraft:cooked_beef
  - minecraft:iron_ingot
  - minecraft:netherite_chestplate
  - minecraft:netherite_upgrade_smithing_template
  - minecraft:ward_armor_trim_smithing_template
  - minecraft:silence_armor_trim_smithing_template
  - minecraft:light_gray_dye
  - minecraft:diorite_stairs
  - minecraft:polished_diorite_stairs
  - minecraft:rotten_flesh
  - minecraft:dirt
  - minecraft:bone
  - koish:example/bronze_ingot
