type: core
pools:
  - rolls: 1
    entries:
      - type: simple
        data:
          type: attribute
          value: { type: "max_mana", operation: "add", value: 100.0, weight: 1 }
        weight: 1
