# 不要修改!
version: 1

# 该文件负责设置「默认元素」
# 当游戏尝试寻找一个元素但不存在时将使用该元素
# id 为 "neutral" 的元素将自动作为默认元素

name: "<color:#faff69>中立"
styles: "<color:#faff69>"

# 元素叠层效果 (暂时失效, 请等待新实现完成)
stack_effects:
  # 最大叠层数量
  max_amount: 10
  # 该元素叠层会在生物上持续多久, 单位为 tick
  disappear_time: 100
  # 叠层的效果
  stages:
    - amount: 5 # 达到指定的叠层数量
      abilities: # 释放的叠层效果技能
        - active/blink
