# 用于配置图鉴系统中每一个 Minecraft 战利品表节点 (class: CatalogItemLootTableNode) 所对应的菜单设置, 以及菜单设置中输入图标的样子

# 这里指定了一个特定的战利品表所使用的菜单设置
#
# key:
#   正则表达式, 用于匹配战利品表的唯一标识
# value:
#   菜单设置的唯一标识, 引用自文件 configs/catalog/item/layout/node/loot_table/menus.yml 中预设的菜单设置 (一级 key)
menu_setting_mappings:
  # chests
  "^minecraft:chests/(?!jungle_temple_dispenser$|spawn_bonus_chest$|trial_chambers/.*$).*$": chest
  "^minecraft:chests/trial_chambers/reward$": vault
  "^minecraft:chests/trial_chambers/reward_ominous$": vault
  "^minecraft:chests/trial_chambers/supply$": chest
  "^minecraft:chests/trial_chambers/corridor$": chest
  "^minecraft:chests/trial_chambers/intersection$": chest
  "^minecraft:chests/trial_chambers/intersection_barrel$": barrel
  "^minecraft:chests/trial_chambers/entrance$": chest
  # entities
  "^minecraft:entities/(?!sheep(/.*)?$).*$": entity
  "^minecraft:entities/sheep/white$": entity

# 这里指定了一个特定的战利品表的菜单设置中的 "input" 的具体样子
#
# key:
#   正则表达式, 用于匹配战利品表的唯一标识
# value:
#   输入图标物品的唯一标识, 引用 configs/item/ 中预设的物品
input_icon_mappings:
  # chests/
  "^minecraft:chests/village/village_armorer$": internal/menu/catalog/default/node/loot_table/chests/village/village_armorer
  "^minecraft:chests/village/village_butcher$": internal/menu/catalog/default/node/loot_table/chests/village/village_butcher
  "^minecraft:chests/village/village_cartographer$": internal/menu/catalog/default/node/loot_table/chests/village/village_cartographer
  "^minecraft:chests/village/village_desert_house$": internal/menu/catalog/default/node/loot_table/chests/village/village_desert_house
  "^minecraft:chests/village/village_fisher$": internal/menu/catalog/default/node/loot_table/chests/village/village_fisher
  "^minecraft:chests/village/village_fletcher$": internal/menu/catalog/default/node/loot_table/chests/village/village_fletcher
  "^minecraft:chests/village/village_mason$": internal/menu/catalog/default/node/loot_table/chests/village/village_mason
  "^minecraft:chests/village/village_plains_house$": internal/menu/catalog/default/node/loot_table/chests/village/village_plains_house
  "^minecraft:chests/village/village_savanna_house$": internal/menu/catalog/default/node/loot_table/chests/village/village_savanna_house
  "^minecraft:chests/village/village_shepherd$": internal/menu/catalog/default/node/loot_table/chests/village/village_shepherd
  "^minecraft:chests/village/village_snowy_house$": internal/menu/catalog/default/node/loot_table/chests/village/village_snowy_house
  "^minecraft:chests/village/village_taiga_house$": internal/menu/catalog/default/node/loot_table/chests/village/village_taiga_house
  "^minecraft:chests/village/village_tannery$": internal/menu/catalog/default/node/loot_table/chests/village/village_tannery
  "^minecraft:chests/village/village_temple$": internal/menu/catalog/default/node/loot_table/chests/village/village_temple
  "^minecraft:chests/village/village_toolsmith$": internal/menu/catalog/default/node/loot_table/chests/village/village_toolsmith
  "^minecraft:chests/village/village_weaponsmith$": internal/menu/catalog/default/node/loot_table/chests/village/village_weaponsmith
  "^minecraft:chests/trial_chambers/reward$": internal/menu/catalog/default/node/loot_table/chests/trial_chambers/reward
  "^minecraft:chests/trial_chambers/reward_ominous$": internal/menu/catalog/default/node/loot_table/chests/trial_chambers/reward_ominous
  "^minecraft:chests/trial_chambers/supply$": internal/menu/catalog/default/node/loot_table/chests/trial_chambers/supply
  "^minecraft:chests/trial_chambers/corridor$": internal/menu/catalog/default/node/loot_table/chests/trial_chambers/corridor
  "^minecraft:chests/trial_chambers/intersection$": internal/menu/catalog/default/node/loot_table/chests/trial_chambers/intersection
  "^minecraft:chests/trial_chambers/intersection_barrel$": internal/menu/catalog/default/node/loot_table/chests/trial_chambers/intersection_barrel
  "^minecraft:chests/trial_chambers/entrance$": internal/menu/catalog/default/node/loot_table/chests/trial_chambers/entrance
  "^minecraft:chests/abandoned_mineshaft$": internal/menu/catalog/default/node/loot_table/chests/abandoned_mineshaft
  "^minecraft:chests/ancient_city$": internal/menu/catalog/default/node/loot_table/chests/ancient_city
  "^minecraft:chests/ancient_city_ice_box$": internal/menu/catalog/default/node/loot_table/chests/ancient_city_ice_box
  "^minecraft:chests/bastion_bridge$": internal/menu/catalog/default/node/loot_table/chests/bastion_bridge
  "^minecraft:chests/bastion_hoglin_stable$": internal/menu/catalog/default/node/loot_table/chests/bastion_hoglin_stable
  "^minecraft:chests/bastion_other$": internal/menu/catalog/default/node/loot_table/chests/bastion_other
  "^minecraft:chests/bastion_treasure$": internal/menu/catalog/default/node/loot_table/chests/bastion_treasure
  "^minecraft:chests/buried_treasure$": internal/menu/catalog/default/node/loot_table/chests/buried_treasure
  "^minecraft:chests/desert_pyramid$": internal/menu/catalog/default/node/loot_table/chests/desert_pyramid
  "^minecraft:chests/end_city_treasure$": internal/menu/catalog/default/node/loot_table/chests/end_city_treasure
  "^minecraft:chests/igloo_chest$": internal/menu/catalog/default/node/loot_table/chests/igloo_chest
  "^minecraft:chests/jungle_temple$": internal/menu/catalog/default/node/loot_table/chests/jungle_temple
  "^minecraft:chests/nether_bridge$": internal/menu/catalog/default/node/loot_table/chests/nether_bridge
  "^minecraft:chests/pillager_outpost$": internal/menu/catalog/default/node/loot_table/chests/pillager_outpost
  "^minecraft:chests/ruined_portal$": internal/menu/catalog/default/node/loot_table/chests/ruined_portal
  "^minecraft:chests/shipwreck_map$": internal/menu/catalog/default/node/loot_table/chests/shipwreck_map
  "^minecraft:chests/shipwreck_supply$": internal/menu/catalog/default/node/loot_table/chests/shipwreck_supply
  "^minecraft:chests/shipwreck_treasure$": internal/menu/catalog/default/node/loot_table/chests/shipwreck_treasure
  "^minecraft:chests/simple_dungeon$": internal/menu/catalog/default/node/loot_table/chests/simple_dungeon
  "^minecraft:chests/stronghold_corridor$": internal/menu/catalog/default/node/loot_table/chests/stronghold_corridor
  "^minecraft:chests/stronghold_crossing$": internal/menu/catalog/default/node/loot_table/chests/stronghold_crossing
  "^minecraft:chests/stronghold_library$": internal/menu/catalog/default/node/loot_table/chests/stronghold_library
  "^minecraft:chests/underwater_ruin_big$": internal/menu/catalog/default/node/loot_table/chests/underwater_ruin_big
  "^minecraft:chests/underwater_ruin_small$": internal/menu/catalog/default/node/loot_table/chests/underwater_ruin_small
  "^minecraft:chests/woodland_mansion$": internal/menu/catalog/default/node/loot_table/chests/woodland_mansion
  # entities/
  "^minecraft:entities/allay$": internal/menu/catalog/default/node/loot_table/entities/allay
  "^minecraft:entities/armadillo$": internal/menu/catalog/default/node/loot_table/entities/armadillo
  "^minecraft:entities/armor_stand$": internal/menu/catalog/default/node/loot_table/entities/armor_stand
  "^minecraft:entities/axolotl$": internal/menu/catalog/default/node/loot_table/entities/axolotl
  "^minecraft:entities/bat$": internal/menu/catalog/default/node/loot_table/entities/bat
  "^minecraft:entities/bee$": internal/menu/catalog/default/node/loot_table/entities/bee
  "^minecraft:entities/blaze$": internal/menu/catalog/default/node/loot_table/entities/blaze
  "^minecraft:entities/bogged$": internal/menu/catalog/default/node/loot_table/entities/bogged
  "^minecraft:entities/breeze$": internal/menu/catalog/default/node/loot_table/entities/breeze
  "^minecraft:entities/camel$": internal/menu/catalog/default/node/loot_table/entities/camel
  "^minecraft:entities/camel_husk$": internal/menu/catalog/default/node/loot_table/entities/camel_husk
  "^minecraft:entities/cat$": internal/menu/catalog/default/node/loot_table/entities/cat
  "^minecraft:entities/cave_spider$": internal/menu/catalog/default/node/loot_table/entities/cave_spider
  "^minecraft:entities/chicken$": internal/menu/catalog/default/node/loot_table/entities/chicken
  "^minecraft:entities/cod$": internal/menu/catalog/default/node/loot_table/entities/cod
  "^minecraft:entities/copper_golem$": internal/menu/catalog/default/node/loot_table/entities/copper_golem
  "^minecraft:entities/cow$": internal/menu/catalog/default/node/loot_table/entities/cow
  "^minecraft:entities/creaking$": internal/menu/catalog/default/node/loot_table/entities/creaking
  "^minecraft:entities/creeper$": internal/menu/catalog/default/node/loot_table/entities/creeper
  "^minecraft:entities/dolphin$": internal/menu/catalog/default/node/loot_table/entities/dolphin
  "^minecraft:entities/donkey$": internal/menu/catalog/default/node/loot_table/entities/donkey
  "^minecraft:entities/drowned$": internal/menu/catalog/default/node/loot_table/entities/drowned
  "^minecraft:entities/elder_guardian$": internal/menu/catalog/default/node/loot_table/entities/elder_guardian
  "^minecraft:entities/ender_dragon$": internal/menu/catalog/default/node/loot_table/entities/ender_dragon
  "^minecraft:entities/enderman$": internal/menu/catalog/default/node/loot_table/entities/enderman
  "^minecraft:entities/endermite$": internal/menu/catalog/default/node/loot_table/entities/endermite
  "^minecraft:entities/evoker$": internal/menu/catalog/default/node/loot_table/entities/evoker
  "^minecraft:entities/fox$": internal/menu/catalog/default/node/loot_table/entities/fox
  "^minecraft:entities/frog$": internal/menu/catalog/default/node/loot_table/entities/frog
  "^minecraft:entities/ghast$": internal/menu/catalog/default/node/loot_table/entities/ghast
  "^minecraft:entities/giant$": internal/menu/catalog/default/node/loot_table/entities/giant
  "^minecraft:entities/glow_squid$": internal/menu/catalog/default/node/loot_table/entities/glow_squid
  "^minecraft:entities/goat$": internal/menu/catalog/default/node/loot_table/entities/goat
  "^minecraft:entities/guardian$": internal/menu/catalog/default/node/loot_table/entities/guardian
  "^minecraft:entities/happy_ghast$": internal/menu/catalog/default/node/loot_table/entities/happy_ghast
  "^minecraft:entities/hoglin$": internal/menu/catalog/default/node/loot_table/entities/hoglin
  "^minecraft:entities/horse$": internal/menu/catalog/default/node/loot_table/entities/horse
  "^minecraft:entities/husk$": internal/menu/catalog/default/node/loot_table/entities/husk
  "^minecraft:entities/illusioner$": internal/menu/catalog/default/node/loot_table/entities/illusioner
  "^minecraft:entities/iron_golem$": internal/menu/catalog/default/node/loot_table/entities/iron_golem
  "^minecraft:entities/llama$": internal/menu/catalog/default/node/loot_table/entities/llama
  "^minecraft:entities/magma_cube$": internal/menu/catalog/default/node/loot_table/entities/magma_cube
  "^minecraft:entities/mannequin$": internal/menu/catalog/default/node/loot_table/entities/mannequin
  "^minecraft:entities/mooshroom$": internal/menu/catalog/default/node/loot_table/entities/mooshroom
  "^minecraft:entities/mule$": internal/menu/catalog/default/node/loot_table/entities/mule
  "^minecraft:entities/nautilus$": internal/menu/catalog/default/node/loot_table/entities/nautilus
  "^minecraft:entities/ocelot$": internal/menu/catalog/default/node/loot_table/entities/ocelot
  "^minecraft:entities/panda$": internal/menu/catalog/default/node/loot_table/entities/panda
  "^minecraft:entities/parched$": internal/menu/catalog/default/node/loot_table/entities/parched
  "^minecraft:entities/parrot$": internal/menu/catalog/default/node/loot_table/entities/parrot
  "^minecraft:entities/phantom$": internal/menu/catalog/default/node/loot_table/entities/phantom
  "^minecraft:entities/pig$": internal/menu/catalog/default/node/loot_table/entities/pig
  "^minecraft:entities/piglin$": internal/menu/catalog/default/node/loot_table/entities/piglin
  "^minecraft:entities/piglin_brute$": internal/menu/catalog/default/node/loot_table/entities/piglin_brute
  "^minecraft:entities/pillager$": internal/menu/catalog/default/node/loot_table/entities/pillager
  "^minecraft:entities/player$": internal/menu/catalog/default/node/loot_table/entities/player
  "^minecraft:entities/polar_bear$": internal/menu/catalog/default/node/loot_table/entities/polar_bear
  "^minecraft:entities/pufferfish$": internal/menu/catalog/default/node/loot_table/entities/pufferfish
  "^minecraft:entities/rabbit$": internal/menu/catalog/default/node/loot_table/entities/rabbit
  "^minecraft:entities/ravager$": internal/menu/catalog/default/node/loot_table/entities/ravager
  "^minecraft:entities/salmon$": internal/menu/catalog/default/node/loot_table/entities/salmon
  "^minecraft:entities/sheep/white$": internal/menu/catalog/default/node/loot_table/entities/sheep
  "^minecraft:entities/shulker$": internal/menu/catalog/default/node/loot_table/entities/shulker
  "^minecraft:entities/silverfish$": internal/menu/catalog/default/node/loot_table/entities/silverfish
  "^minecraft:entities/skeleton_horse$": internal/menu/catalog/default/node/loot_table/entities/skeleton_horse
  "^minecraft:entities/skeleton$": internal/menu/catalog/default/node/loot_table/entities/skeleton
  "^minecraft:entities/slime$": internal/menu/catalog/default/node/loot_table/entities/slime
  "^minecraft:entities/sniffer$": internal/menu/catalog/default/node/loot_table/entities/sniffer
  "^minecraft:entities/snow_golem$": internal/menu/catalog/default/node/loot_table/entities/snow_golem
  "^minecraft:entities/spider$": internal/menu/catalog/default/node/loot_table/entities/spider
  "^minecraft:entities/squid$": internal/menu/catalog/default/node/loot_table/entities/squid
  "^minecraft:entities/stray$": internal/menu/catalog/default/node/loot_table/entities/stray
  "^minecraft:entities/strider$": internal/menu/catalog/default/node/loot_table/entities/strider
  "^minecraft:entities/tadpole$": internal/menu/catalog/default/node/loot_table/entities/tadpole
  "^minecraft:entities/trader_llama$": internal/menu/catalog/default/node/loot_table/entities/trader_llama
  "^minecraft:entities/tropical_fish$": internal/menu/catalog/default/node/loot_table/entities/tropical_fish
  "^minecraft:entities/turtle$": internal/menu/catalog/default/node/loot_table/entities/turtle
  "^minecraft:entities/vex$": internal/menu/catalog/default/node/loot_table/entities/vex
  "^minecraft:entities/villager$": internal/menu/catalog/default/node/loot_table/entities/villager
  "^minecraft:entities/vindicator$": internal/menu/catalog/default/node/loot_table/entities/vindicator
  "^minecraft:entities/wandering_trader$": internal/menu/catalog/default/node/loot_table/entities/wandering_trader
  "^minecraft:entities/warden$": internal/menu/catalog/default/node/loot_table/entities/warden
  "^minecraft:entities/witch$": internal/menu/catalog/default/node/loot_table/entities/witch
  "^minecraft:entities/wither_skeleton$": internal/menu/catalog/default/node/loot_table/entities/wither_skeleton
  "^minecraft:entities/wither$": internal/menu/catalog/default/node/loot_table/entities/wither
  "^minecraft:entities/wolf$": internal/menu/catalog/default/node/loot_table/entities/wolf
  "^minecraft:entities/zoglin$": internal/menu/catalog/default/node/loot_table/entities/zoglin
  "^minecraft:entities/zombie_horse$": internal/menu/catalog/default/node/loot_table/entities/zombie_horse
  "^minecraft:entities/zombie_nautilus$": internal/menu/catalog/default/node/loot_table/entities/zombie_nautilus
  "^minecraft:entities/zombie_villager$": internal/menu/catalog/default/node/loot_table/entities/zombie_villager
  "^minecraft:entities/zombie$": internal/menu/catalog/default/node/loot_table/entities/zombie
  "^minecraft:entities/zombified_piglin$": internal/menu/catalog/default/node/loot_table/entities/zombified_piglin