# 不要修改!
version: 1

# 玩家空手攻击 (手持非 `koish:weapon` 物品时左键) 的冷却时间 (tick).
player_intrinsic_attack_cooldown: 5

# 伤害规则相关.
rules:

  # 对于某一元素类型, 其伤害计算时, 最终是否四舍五入到整数位.
  rounding_damage: true

  # 对于某一元素类型, 其最小伤害.
  least_damage: 1.0

  # 对于某一元素类型, 计算其有效防御的公式.
  #
  # 可用参数:
  # 请注意: 下列各属性均为(本元素+通用元素), 不会小于0(属性值为负时会被置零)
  # q.defense
  #   受伤者该元素的防御力属性值
  # q.defense_penetration
  #   伤害元数据中该元素的防御穿透
  # q.defense_penetration_rate
  #   伤害元数据中该元素的防御穿透率
  valid_defense_formula: "math.max(q.defense - q.defense_penetration, 0.0) * (1.0 - q.defense_penetration_rate)"

  # 对于某一元素类型, 计算其防御后伤害的公式.
  #
  # 可用参数:
  # q.original_damage
  #   原始伤害
  # q.valid_defense
  #   受伤者该元素的有效防御
  damage_after_defense_formula: "math.max(q.original_damage * (1.0 - (q.valid_defense / (q.original_damage + q.valid_defense))), 0.0)"

  # 计算拉弓力度的公式.
  #
  # 可用参数:
  # q.use_ticks
  #   玩家拉弓释放时, 累计长按使用的时间, 单位 tick
  bow_force_formula: "math.clamp((q.use_ticks * q.use_ticks / 400.0 + q.use_ticks / 10.0) / 3.0, 0.0, 1.0)"

# 盔甲耐久度损失相关
equipment:
  # 每点伤害损失耐久度
  amount_per_damage: 0.25
  # 单次伤害损失耐久度最小值
  min_amount: 1
  # 单次伤害损失耐久度最大值
  max_amount: 2147483647
  # 不会使盔甲损失耐久的伤害类型
  # 默认列表为默认 damage_type_mappings.yml 文件中防御穿透率为 1.0 的伤害类型
  no_durability_loss_damage_types:
    - cactus
    - campfire
    - cramming
    - drown
    - dry_out
    - ender_pearl
    - fall
    - falling_anvil
    - falling_block
    - falling_stalactite
    - fly_into_wall
    - freeze
    - generic
    - generic_kill
    - hot_floor
    - in_fire
    - in_wall
    - indirect_magic
    - lava
    - lightning_bolt
    - magic
    - on_fire
    - out_of_world
    - outside_border
    - stalagmite
    - starve
    - wither

# 属性修饰符来源
attribute_modifier_source:
  # 来源于状态效果
  effect:
    resistance:
      - id: "incoming_damage_rate"
        operation: add
        value: 0
        element: neutral
        number_modifier:
          type: effect_level_linear_bonus
          per_level: 0.2
    strength:
      - id: "attack_damage"
        operation: add
        lower: 0
        upper: 0
        element: neutral
        number_modifier:
          type: effect_level_linear_bonus
          per_level: 3
      - id: "attack_damage"
        operation: add
        lower: 0
        upper: 0
        element: water
        number_modifier:
          type: effect_level_linear_bonus
          per_level: 5
      - id: "attack_damage"
        operation: add
        lower: 0
        upper: 0
        element: fire
        number_modifier:
          type: effect_level_linear_bonus
          per_level: 1
    weakness:
      - id: "attack_damage"
        operation: add
        lower: 0
        upper: 0
        element: neutral
        number_modifier:
          type: effect_level_linear_bonus
          per_level: -4
    haste:
      - id: "attack_cooldown_rate"
        operation: add
        value: 0
        number_modifier:
          type: effect_level_linear_bonus
          per_level: -0.1
    mining_fatigue:
      - id: "attack_cooldown_rate"
        operation: add
        value: 0
        number_modifier:
          type: effect_level_linear_bonus
          per_level: 0.1

# TODO 生物护甲、潜影贝盖壳

display2:
  normal:
    type: text_display
    settings:
      billboard: center
      brightness: default
      glow_color_override: -1
      height: 0.0
      width: 0.0
      shadow_radius: 0.0
      shadow_strength: 1.0
      view_range: 1.0
      text_alignment: center
      background: 0
      default_background: false
      line_width: 200
      is_see_through: true
      has_text_shadow: true
      text:
        type: damage_hologram_normal_attack
        # 伤害显示总文本.
        final_text: <damage_value_text>
        # 元素文本.
        # 支持占位符:
        # - <element_name> 元素名
        # - <element_style> 元素风格
        # - <damage_value> 该元素类型具体伤害值
        damage_value_text: "<element_style><damage_value:0>"
        # 是否合并各元素伤害值.
        is_damage_value_merged: false
        # 各元素类型的伤害文本之间的分隔字符串.
        # 仅当 merge_damage_value 为 false 时有意义.
        separator: " "
    frames:
      0:
        start_interpolation: 0
        interpolation_duration: 0
        teleport_duration: 0
        transformation:
          translation: [ .0, -1.0, .0 ]
          scale: [ 1.5, 1.5, 1.5 ]
          left_rotation: [ .0, .0, .0, 1.0 ]
          right_rotation: [ .0, .0, .0, 1.0 ]
      2:
        start_interpolation: 0
        interpolation_duration: 5
        teleport_duration: 0
        transformation:
          translation: [ .0, -0.5, .0 ]
          scale: [ 2.5, 2.5, 2.5 ]
          left_rotation: [ .0, .0, .0, 1.0 ]
          right_rotation: [ .0, .0, .0, 1.0 ]
      8:
        start_interpolation: 0
        interpolation_duration: 20
        teleport_duration: 0
        transformation:
          translation: [ .0, 0.5, .0 ]
          scale: [ 1.0, 1.0, 1.0 ]
          left_rotation: [ .0, .0, .0, 1.0 ]
          right_rotation: [ .0, .0, .0, 1.0 ]
  positive_critical_strike:
    type: text_display
    settings:
      billboard: center
      background: 0
      is_see_through: true
      has_text_shadow: true
      text:
        type: damage_hologram_critical_strike
        # 伤害显示总文本.
        final_text: <critical_strike_style><critical_strike_text><damage_value_text>
        # 暴击状态风格.
        critical_strike_style: <bold>
        # 暴击状态文本.
        critical_strike_text: <color:#FF9900>💥</color:#FF9900>
        # 元素文本.
        # 支持占位符:
        # - <element_name> 元素名
        # - <element_style> 元素风格
        # - <damage_value> 该元素类型具体伤害值
        damage_value_text: "<element_style><damage_value:0>"
        # 是否合并各元素伤害值.
        merge_damage_value: false
        # 各元素类型的伤害文本之间的分隔字符串.
        # 仅当 merge_damage_value 为 false 时有意义.
        separator: " "
    frames:
      0:
        interpolation_duration: 0
        transformation:
          translation: [ .0, -1.0, .0 ]
          scale: [ 1.5, 1.5, 1.5 ]
      2:
        interpolation_duration: 5
        transformation:
          translation: [ .0, -0.5, .0 ]
          scale: [ 4.5, 4.5, 4.5 ]
      8:
        interpolation_duration: 20
        transformation:
          translation: [ .0, 0.5, .0 ]
  negative_critical_strike:
    type: text_display
    settings:
      billboard: center
      background: 0
      is_see_through: true
      has_text_shadow: true
      text:
        type: damage_hologram_critical_strike
        final_text: <critical_strike_style><critical_strike_text><damage_value_text>
        critical_strike_style: <bold>
        critical_strike_text: <color:#02AFFF>💥</color:#02AFFF>
        damage_value_text: "<element_style><damage_value:0>"
        merge_damage_value: false
        separator: " "
    frames:
      0:
        interpolation_duration: 0
        transformation:
          translation: [ .0, -1.0, .0 ]
          scale: [ 1.5, 1.5, 1.5 ]
      2:
        interpolation_duration: 5
        transformation:
          translation: [ .0, -0.5, .0 ]
          scale: [ 4.5, 4.5, 4.5 ]
      8:
        interpolation_duration: 20
        transformation:
          translation: [ .0, 0.5, .0 ]