# 不要修改!
version: 1

# 映射:
#   key: direct_entity
#   val: damage_metadata
#
# 使用场景:
# damage_source 的 direct_entity 存在但 causing_entity 不存在. 例如:
# - 发射器发射弹射物 (即使是玩家触发的发射器. 说不定哪天可以“追踪”了, 谁知道呢)
# - 发射器发射TNT
# - 红石激活TNT

# 这一级的每一个 node 为一种实体类型的伤害映射
# node key 为发起攻击的实体类型的 id
# node value 为对应实体类型的伤害映射
tnt:
  一般:
    damage_metadata:
      type: vanilla
      damage_tags: [ ]
      element: neutral
      critical_strike_metadata:
        chance: 0.0
end_crystal:
  一般:
    damage_metadata:
      type: vanilla
      damage_tags: [ ]
      element: neutral
      critical_strike_metadata:
        chance: 0.0
arrow:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 1.0, max: 1.0 }
      critical_strike_metadata:
        chance: 0.0
egg:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 0.0, max: 0.0 }
      critical_strike_metadata:
        chance: 0.0
ender_pearl:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 0.0, max: 0.0 }
      critical_strike_metadata:
        chance: 0.0
fireball:
  爆炸:
    predicates:
      damage_type:
        - explosion
        - player_explosion
    damage_metadata:
      type: vanilla
      damage_tags: [ ]
      element: fire
      critical_strike_metadata:
        chance: 0.0
  接触:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        fire: { min: 6.0, max: 6.0 }
      critical_strike_metadata:
        chance: 0.0
firework_rocket:
  一般:
    damage_metadata:
      type: vanilla
      damage_tags: [ ]
      element: neutral
      critical_strike_metadata:
        chance: 0.0
area_effect_cloud:
  一般:
    damage_metadata:
      type: vanilla
      damage_tags: [ ]
      element: neutral
      critical_strike_metadata:
        chance: 0.0
llama_spit:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 1.0, max: 1.0 }
      critical_strike_metadata:
        chance: 0.0
shulker_bullet:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 4.0, max: 4.0 }
      critical_strike_metadata:
        chance: 0.0
small_fireball:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        fire: { min: 5.0, max: 5.0 }
      critical_strike_metadata:
        chance: 0.0
snowball:
  攻击烈焰人:
    predicates:
      victim_entity_type:
        - blaze
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 3.0, max: 3.0 }
      critical_strike_metadata:
        chance: 0.0
  攻击其他实体:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 0.0, max: 0.0 }
      critical_strike_metadata:
        chance: 0.0
potion:
  一般:
    damage_metadata:
      type: vanilla
      damage_tags: [ ]
      element: neutral
      critical_strike_metadata:
        chance: 0.0
trident:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 8.0, max: 8.0 }
      critical_strike_metadata:
        chance: 0.0
wind_charge:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        wind: { min: 1.0, max: 1.0 }
      critical_strike_metadata:
        chance: 0.0
breeze_wind_charge:
  一般:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        wind: { min: 1.0, max: 1.0 }
      critical_strike_metadata:
        chance: 0.0
wither_skull:
  爆炸:
    predicates:
      damage_type:
        - explosion
        - player_explosion
    damage_metadata:
      type: vanilla
      damage_tags: [ ]
      element: neutral
      critical_strike_metadata:
        chance: 0.0
  接触:
    damage_metadata:
      type: direct
      damage_tags: [ ]
      damage_bundle:
        neutral: { min: 8.0, max: 8.0 }
      critical_strike_metadata:
        chance: 0.0
