name: Wakame
version: "{{ version }}"
main: cc.mewcraft.wakame.KoishPlugin
bootstrapper: cc.mewcraft.wakame.KoishBootstrap
loader: cc.mewcraft.wakame.KoishLoader
description: "{{ description }}"
api-version: 1.21
author: Nailm
load: STARTUP
dependencies:
  server:
    AdventureLevel:
      required: false
      load: BEFORE # Koish 需要访问其事件
    ChestSort:
      required: false
      load: OMIT
    Economy:
      required: false
      load: OMIT
    EconomyBridge:
      required: false
      load: BEFORE # Koish 需要访问其 ItemManager
    ExcellentShop:
      required: false
      join-classpath: false
      load: AFTER # ExcellentShop 需要访问 Koish 注册的 ItemHandler
    ExcellentCrates:
      required: false
      join-classpath: false
      load: AFTER # ExcellentCrates 需要访问 Koish 注册的 ItemHandler
    LuckPerms:
      required: false
      load: OMIT
    MythicMobs:
      required: false
      load: OMIT
    PlaceholderAPI:
      required: false
      load: OMIT
    Towny:
      required: false
      load: OMIT
    TownyFlight:
      required: false
      load: OMIT
    Vault:
      required: false
      load: OMIT
    WorldGuard:
      required: false
      load: OMIT
