name: Wakame
version: "{{ version }}"
main: cc.mewcraft.wakame.KoishPlugin
bootstrapper: cc.mewcraft.wakame.KoishBootstrap
loader: cc.mewcraft.wakame.KoishLoader
description: "{{ description }}"
api-version: 1.21.11
author: Nailm
dependencies:
  server:
    AdventureLevel:
      required: false
      load: BEFORE # Koish 需要访问其事件
    AuraSkills:
      required: false
      load: BEFORE
    BetonQuest:
      required: false
      load: BEFORE
    BetterGUI:
      required: false
      load: OMIT
    BetterHud:
      required: false
      load: OMIT
    BreweryX:
      required: false
      load: BEFORE # Koish 需要访问其 PluginItem 并注册实例
    CarbonChat:
      required: false
      load: OMIT
    ChestShop:
      required: false
      load: OMIT # 只监听其事件, 所以顺序无关紧要
    ChestSort:
      required: false
      load: OMIT
    CraftEngine:
      required: false
      load: OMIT
    Economy:
      required: false
      load: OMIT
    ExcellentShop:
      required: false
      join-classpath: false
      load: AFTER # ExcellentShop 需要访问 Koish 注册的 ItemHandler
    ExcellentCrates:
      required: false
      join-classpath: false
      load: AFTER # ExcellentCrates 需要访问 Koish 注册的 ItemHandler
    ExtraContexts:
      required: false
      load: OMIT
    HibiscusCommons:
      required: false
      load: AFTER # HibiscusCommons 需要访问 Koish 注册的 Hook
    HuskHomes:
      required: false
      load: OMIT
    HuskSync:
      required: false
      load: OMIT
    LuckPerms:
      required: false
      load: OMIT
    MythicDungeons:
      required: false
      load: OMIT # 游戏中才需要用到其 API
    MythicMobs:
      required: false
      load: OMIT
    nightcore:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: OMIT
    PlotSquared:
      required: false
      load: OMIT
    Portals:
      required: false
      load: OMIT
    QuickShop-Hikari:
      required: false
      load: OMIT # 只监听其事件, 所以顺序无关紧要
    TheBrewingProject:
      required: false
      load: BEFORE
    Towny:
      required: false
      load: OMIT
    TownyFlight:
      required: false
      load: OMIT
    Vault:
      required: false
      load: OMIT
    WorldGuard:
      required: false
      load: OMIT
