name: Wakame
version: "{{ version }}"
main: cc.mewcraft.wakame.KoishPlugin
bootstrapper: cc.mewcraft.wakame.KoishBootstrap
loader: cc.mewcraft.wakame.KoishLoader
description: "{{ description }}"
api-version: 1.21.8
author: Nailm
dependencies:
  server:
    AdventureLevel:
      required: false
      load: BEFORE # Koish 需要访问其事件
    AuraSkills:
      required: false
      load: OMIT
    BetterHud:
      required: false
      load: OMIT
    BreweryX:
      required: false
      load: BEFORE # Koish 需要访问其 PluginItem 并注册实例
    ChestShop:
      required: false
      load: OMIT # 只监听其事件, 所以顺序无关紧要
    ChestSort:
      required: false
      load: OMIT
    CraftEngine:
      required: false
      load: OMIT # 只在服务端完全启动后调其 API
    Economy:
      required: false
      load: OMIT
    EconomyBridge:
      required: false
      load: BEFORE # Koish 需要访问其 ItemManager
    ExcellentShop:
      required: false
      join-classpath: false
      load: AFTER # ExcellentShop 需要访问 Koish 注册的 ItemHandler
    ExcellentCrates:
      required: false
      join-classpath: false
      load: AFTER # ExcellentCrates 需要访问 Koish 注册的 ItemHandler
    HuskSync:
      required: false
      load: OMIT
    LuckPerms:
      required: false
      load: OMIT
    MythicMobs:
      required: false
      load: OMIT
    PlaceholderAPI:
      required: false
      load: OMIT
    QuickShop-Hikari:
      required: false
      load: OMIT # 只监听其事件, 所以顺序无关紧要
    TheBrewingProject:
      required: false
      load: BEFORE
    Towny:
      required: false
      load: OMIT
    TownyFlight:
      required: false
      load: OMIT
    Vault:
      required: false
      load: OMIT
    WorldGuard:
      required: false
      load: OMIT
