name: ExtraContexts
version: 0.0.1
description: Adds key-value context support to LuckPerms
authors: [ Nailm ]
main: cc.mewcraft.extracontexts.paper.ExtraContextsPaperPlugin
api-version: 1.21.8
dependencies:
  server:
    LuckPerms:
      required: true
      load: OMIT
