# 此处引用 menu_settings.yml 中预设的菜单布局
menu_settings:
  "^minecraft:chests/desert_pyramid$": loot_table_recipe_chest
icon:
  "^minecraft:chests/desert_pyramid$": internal:menu/catalog/loot_table/chests/desert_pyramid