# 锻造升级配方, 参考: https://minecraft.wiki/w/Recipe#smithing_transform
type: smithing_transform

# 表示要被锻造升级的基础物品
base:
  - minecraft:cobblestone
  - minecraft:stone

# 表示升级基础物品时所需的锻造原材料
addition: minecraft:ender_pearl

# 经过锻造升级后得到的输出物品
result:
  item: minecraft:end_stone
  amount: 1