# 锻造升级配方, 参考: https://minecraft.wiki/w/Recipe#smithing_transform
type: smithing_transform

# 表示要被锻造升级的基础材料
base:
  - minecraft:cobblestone
  - minecraft:stone

# 表示锻造升级所需要的额外材料
addition:
  - minecraft:ender_pearl

# 表示锻造升级所需要的模板物品
template:
  - minecraft:netherite_ingot

# 经过锻造升级后得到的输出物品
result:
  item: minecraft:end_stone
  amount: 1