# 主要的菜单的设置
primary_menu_settings:

  # 菜单的标题
  title: "定制工作台: example"

  # .: 背景
  # i: 装备输入
  # o: 装备输出
  # x: 子菜单
  # <: 上一页
  # >: 下一页
  structure:
    - ". . . x x x . . ."
    - ". . . x x x . . ."
    - ". i . x x x . o ."
    - ". . . x x x . . ."
    - ". . . x x x . . ."
    - ". . . < # > . . ."

  # background: 背景
  # prev_page: 上一页
  # next_page: 下一页
  # input_ok: 输入
  # input_empty: 输入
  # output_empty: 输出
  # output_failure: 输出
  # output_ok_confirmed: 输出
  # output_ok_unconfirmed: 输出
  # output_insufficient_resource: 输出
  icons:
    background: "internal/menu/common/default/background"
    prev_page: "internal/menu/common/default/prev_page"
    next_page: "internal/menu/common/default/next_page"
    input_ok: "internal/menu/modding/default/input_ok"
    input_empty: "internal/menu/modding/default/input_empty"
    output_empty: "internal/menu/modding/default/output_empty"
    output_failure: "internal/menu/modding/default/output_failure"
    output_ok_confirmed: "internal/menu/modding/default/output_ok_confirmed"
    output_ok_unconfirmed: "internal/menu/modding/default/output_ok_unconfirmed"
    output_insufficient_resource: "internal/menu/modding/default/output_insufficient_resource"

# 用于更换核心的菜单的设置
replace_menu_settings:

  # 无实际作用
  title: "DO_NOT_USE"

  # a: 核心
  # b: 输入
  # *: 兼容性检查
  structure: [ "a * b" ]

  # compatibility_view: 兼容性检查
  # core_view: 目标核心
  # core_unusable: 不可用核心
  # core_usable: 可用核心
  icons:
    compatibility_view: "internal/menu/modding/default/compatibility_view"
    core_view: "internal/menu/modding/default/core_view"
    core_unusable: "internal/menu/modding/default/core_unusable"
    core_usable: "internal/menu/modding/default/core_usable"

# 物品的重铸次数的计算方式
# 可用的计算方式:
# - PLUS_ONE: 每次重铸物品固定增加 1 重铸次数
# - CORE_SUM: 每次重铸物品动态增加 ∑(参与定制的核心的重铸次数) + 1
reforge_count_add_method: PLUS_ONE

# 稀有度->数值的映射表.
# 可用于所有的自定义函数.
rarity_number_mapping:
  common: 1.0
  uncommon: 1.5
  rare: 2.0
  epic: 2.5
  ancient: 3.0

# 在这里设置完成定制操作所需要消耗的货币资源.
# 如果玩家没有足够的货币资源, 合并将算作失败.
#
# 计算函数, 用于计算完成整个物品定制的总花费.
#
# 可用参数:
# query.source_item_rarity()
#   被定制物品的稀有度所映射的数值
# query.source_item_level()
#   被定制物品的等级
# query.source_item_total_core_container_count()
#   被定制物品的核孔的数量
# query.source_item_changeable_core_container_count()
#   被定制物品上可以被定制的核孔的数量
# query.source_item_changed_core_container_count()
#   被定制物品上参与了定制的核孔的数量
# query.source_item_changed_core_container_cost()
#   被定制物品上参与了定制的核孔的总花费
currency_cost: 200.0 * query.source_item_rarity()
  + 100.0 * query.source_item_changed_core_container_count()
  + query.source_item_changed_core_container_cost()
