# 用于配置图鉴系统中 chests 战利品表的相关设置

# 实际上, 一个文件可以包含所有的战利品表, 不止唯一标识为 chests/ 开头的, 这里的默认配置分文件是最佳实践, 可以方便进行配置工作

# 程序上的设计是自动根据这里的 key 读取对应的原版战利品表, 然后给他们分配对应的菜单布局和输入图标
# 在读取原版战利品表时, 会自动展开其所有内容物, 并构建出一个用于查询 "物品来源&用途" 的图结构

# 这里指定了一个特定的战利品表所使用的菜单布局
# key 是一个正则表达式, 用于匹配战利品表的唯一标识
# value 是菜单布局的唯一标识, 引用 configs/catalog/item/menu_settings.yml 中预设的菜单布局
menu_setting_mappings:
  "^minecraft:chests/(?!jungle_temple_dispenser$|spawn_bonus_chest$|trial_chambers/.*$).*$": loot_table_recipe_chest
  "^minecraft:chests/trial_chambers/reward$": loot_table_recipe_vault
  "^minecraft:chests/trial_chambers/reward_ominous$": loot_table_recipe_vault
  "^minecraft:chests/trial_chambers/supply$": loot_table_recipe_chest
  "^minecraft:chests/trial_chambers/corridor$": loot_table_recipe_chest
  "^minecraft:chests/trial_chambers/intersection$": loot_table_recipe_chest
  "^minecraft:chests/trial_chambers/intersection_barrel$": loot_table_recipe_barrel
  "^minecraft:chests/trial_chambers/entrance$": loot_table_recipe_chest

# 这里指定了一个特定的战利品表所使用的输入图标, 对应菜单布局中的 "input" 的具体样子
# key 是一个正则表达式, 用于匹配战利品表的唯一标识
# value 是输入图标物品的唯一标识, 引用 configs/item/ 中预设的物品
input_icon_mappings:
  # 村庄
  "^minecraft:chests/village/village_armorer$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_armorer
  "^minecraft:chests/village/village_butcher$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_butcher
  "^minecraft:chests/village/village_cartographer$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_cartographer
  "^minecraft:chests/village/village_desert_house$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_desert_house
  "^minecraft:chests/village/village_fisher$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_fisher
  "^minecraft:chests/village/village_fletcher$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_fletcher
  "^minecraft:chests/village/village_mason$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_mason
  "^minecraft:chests/village/village_plains_house$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_plains_house
  "^minecraft:chests/village/village_savanna_house$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_savanna_house
  "^minecraft:chests/village/village_shepherd$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_shepherd
  "^minecraft:chests/village/village_snowy_house$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_snowy_house
  "^minecraft:chests/village/village_taiga_house$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_taiga_house
  "^minecraft:chests/village/village_tannery$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_tannery
  "^minecraft:chests/village/village_temple$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_temple
  "^minecraft:chests/village/village_toolsmith$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_toolsmith
  "^minecraft:chests/village/village_weaponsmith$": internal/menu/catalog/default/recipe/loot_table/chests/village/village_weaponsmith
  # 试炼密室
  "^minecraft:chests/trial_chambers/reward$": internal/menu/catalog/default/recipe/loot_table/chests/trial_chambers/reward
  "^minecraft:chests/trial_chambers/reward_ominous$": internal/menu/catalog/default/recipe/loot_table/chests/trial_chambers/reward_ominous
  "^minecraft:chests/trial_chambers/supply$": internal/menu/catalog/default/recipe/loot_table/chests/trial_chambers/supply
  "^minecraft:chests/trial_chambers/corridor$": internal/menu/catalog/default/recipe/loot_table/chests/trial_chambers/corridor
  "^minecraft:chests/trial_chambers/intersection$": internal/menu/catalog/default/recipe/loot_table/chests/trial_chambers/intersection
  "^minecraft:chests/trial_chambers/intersection_barrel$": internal/menu/catalog/default/recipe/loot_table/chests/trial_chambers/intersection_barrel
  "^minecraft:chests/trial_chambers/entrance$": internal/menu/catalog/default/recipe/loot_table/chests/trial_chambers/entrance
  # 其他
  "^minecraft:chests/abandoned_mineshaft$": internal/menu/catalog/default/recipe/loot_table/chests/abandoned_mineshaft
  "^minecraft:chests/ancient_city$": internal/menu/catalog/default/recipe/loot_table/chests/ancient_city
  "^minecraft:chests/ancient_city_ice_box$": internal/menu/catalog/default/recipe/loot_table/chests/ancient_city_ice_box
  "^minecraft:chests/bastion_bridge$": internal/menu/catalog/default/recipe/loot_table/chests/bastion_bridge
  "^minecraft:chests/bastion_hoglin_stable$": internal/menu/catalog/default/recipe/loot_table/chests/bastion_hoglin_stable
  "^minecraft:chests/bastion_other$": internal/menu/catalog/default/recipe/loot_table/chests/bastion_other
  "^minecraft:chests/bastion_treasure$": internal/menu/catalog/default/recipe/loot_table/chests/bastion_treasure
  "^minecraft:chests/buried_treasure$": internal/menu/catalog/default/recipe/loot_table/chests/buried_treasure
  "^minecraft:chests/desert_pyramid$": internal/menu/catalog/default/recipe/loot_table/chests/desert_pyramid
  "^minecraft:chests/end_city_treasure$": internal/menu/catalog/default/recipe/loot_table/chests/end_city_treasure
  "^minecraft:chests/igloo_chest$": internal/menu/catalog/default/recipe/loot_table/chests/igloo_chest
  "^minecraft:chests/jungle_temple$": internal/menu/catalog/default/recipe/loot_table/chests/jungle_temple
  "^minecraft:chests/nether_bridge$": internal/menu/catalog/default/recipe/loot_table/chests/nether_bridge
  "^minecraft:chests/pillager_outpost$": internal/menu/catalog/default/recipe/loot_table/chests/pillager_outpost
  "^minecraft:chests/ruined_portal$": internal/menu/catalog/default/recipe/loot_table/chests/ruined_portal
  "^minecraft:chests/shipwreck_map$": internal/menu/catalog/default/recipe/loot_table/chests/shipwreck_map
  "^minecraft:chests/shipwreck_supply$": internal/menu/catalog/default/recipe/loot_table/chests/shipwreck_supply
  "^minecraft:chests/shipwreck_treasure$": internal/menu/catalog/default/recipe/loot_table/chests/shipwreck_treasure
  "^minecraft:chests/simple_dungeon$": internal/menu/catalog/default/recipe/loot_table/chests/simple_dungeon
  "^minecraft:chests/stronghold_corridor$": internal/menu/catalog/default/recipe/loot_table/chests/stronghold_corridor
  "^minecraft:chests/stronghold_crossing$": internal/menu/catalog/default/recipe/loot_table/chests/stronghold_crossing
  "^minecraft:chests/stronghold_library$": internal/menu/catalog/default/recipe/loot_table/chests/stronghold_library
  "^minecraft:chests/underwater_ruin_big$": internal/menu/catalog/default/recipe/loot_table/chests/underwater_ruin_big
  "^minecraft:chests/underwater_ruin_small$": internal/menu/catalog/default/recipe/loot_table/chests/underwater_ruin_small
  "^minecraft:chests/woodland_mansion$": internal/menu/catalog/default/recipe/loot_table/chests/woodland_mansion
