# 这里不需要 base, 因为物品数据将基于合并后的核心生成.

slot_display_name: "<white>结果: <green>合并就绪"

# 额外占位符
# {item_lore}
# {type_description}
# {cost_description}
# {result_description}
slot_display_lore:
  - "{item_lore}"
  - ""
  - "{type_description}"
  - "{cost_description}"
  - "{result_description}"
  - ""
  - "<!i><aqua>再次点击确认合并"
