# 不要修改!
version: 1

# 该文件是默认的稀有度, 不可删除
# 该文件名必须为 “common”, 否则 Koish 将强制关服

# 该稀有度的数字 id, 一旦创建好世界不要再修改
binary_index: 0

# 该稀有度的展示名字
display_name: "<color:#c7c7c7>普通"

# 该稀有度的风格样式
# 注意, 该风格样式跟上面的 display_name 没有关系
# 该风格样式将应用于诸如物品名字之类的文本上, 例如让具有普通稀有度的物品名字为白色, 而稀有的为青色
styles: "<color:#c7c7c7>"

# 该稀有度的发光颜色
glow_color: WHITE
