# 不要修改!
version: 1

# id: `custom_name`
custom_name:
  namespace: vanilla
  tooltip: "定制名: <value>"

# id: `item_name`
item_name:
  namespace: vanilla
  tooltip: "物品名: <value>"

# id: `lore`
lore:
  namespace: general
  tooltip:
    line: "<line>"
    header: [ ]
    bottom: [ ]
