# 不要修改!
version: 1

# id: `custom_name`
custom_name:
  namespace: vanilla
  # 可用标签
  # <value> 物品的 `minecraft:custom_name`
  tooltip: "<!i><gray>定制名: <value>"

# id: `item_name`
item_name:
  namespace: vanilla
  # 可用标签
  # <value> 物品的 `minecraft:item_name`
  tooltip: "<!i><gray>物品名: <value>"

# id: `lore`
lore:
  namespace: general
  # 可用标签：
  # <line> 描述内容
  tooltip:
    line: "<dark_gray><line>"
    header: []
    bottom: []
