# Use case: 新的头盔

base: leather_helmet

slot: minecraft:head

item_name: "青铜头盔"

level:
  base: CONTEXT
  float_chance: 0.15
  float_amount: "[-2,3]"
  max: 30

rarity:
  type: dynamic
  value: "station"

elements:
  type: dynamic
  value: element/simple_element_loot

kizami:
  type: dynamic
  value: kizami/simple_kizami_loot

cores:
  type: dynamic
  value:
    test_1: core/simple_core_loot
