package cc.mewcraft.wakame

import org.slf4j.LoggerFactory
import xyz.jpenilla.gremlin.runtime.DependencyCache
import xyz.jpenilla.gremlin.runtime.DependencyResolver
import xyz.jpenilla.gremlin.runtime.DependencySet
import xyz.jpenilla.gremlin.runtime.logging.Slf4jGremlinLogger
import java.nio.file.Path

/**
 * Gremlin runtime helper for Koish.
 *
 * This reads the dependency descriptor generated by the Gremlin Gradle plugin
 * (see `tasks.writeDependencies` in `koish-plugin/build.gradle.kts`),
 * downloads any missing jars into a cache under the plugin's data folder,
 * and returns the resolved jar file paths.
 */
internal object KoishDependencies {

    private const val DEPENDENCIES_RESOURCE = "koish-dependencies.txt"

    /**
     * Resolve all Gremlin-managed dependencies into the given cache directory.
     *
     * @param cacheDir directory under the plugin data folder to store jars, e.g. `<data>/libraries`.
     * @return set of paths to all resolved jar files.
     */
    @JvmStatic
    fun resolve(cacheDir: Path): Set<Path> {
        val deps = DependencySet.readFromClasspathResource(KoishDependencies::class.java.classLoader, DEPENDENCIES_RESOURCE)
        val cache = DependencyCache(cacheDir)
        val logger = LoggerFactory.getLogger(KoishDependencies::class.java.simpleName)
        val files: Set<Path>
        DependencyResolver(Slf4jGremlinLogger(logger)).use { downloader ->
            files = downloader.resolve(deps, cache).jarFiles()
        }
        cache.cleanup()
        return files
    }
}