# 全局配置文件

# 调试模式开关
# 不完全支持热重载!
debug: true

# 性能设置
performance: { }

# 所使用的经济系统
# 可用选项:
# ECONOMY - Economy 插件的账户余额
# VANILLA - Minecraft 的原版经验等级
# ZERO - 无经济系统 (永远为 0)
economy_provider: VANILLA

# 玩家等级如何计算
#
# 可用选项:
# ADVENTURE - AdventureLevel 插件的冒险等级
# VANILLA - Minecraft 的原版经验等级
# ZERO - 无等级 (永远为 0)
player_level_provider: VANILLA

# 只有物品的所有者可以拾起死亡掉落的物品
only_owner_can_pickup_death_drops: false

# 要求玩家必须在潜行状态下才能够破坏盔甲架
require_sneaking_to_break_armor_stand: false
