# 全局配置文件

debug: true # FIXME: Renderer does not work in debug mode

resource_pack:
  auto_upload:
    enabled: true
    service: self_host
    host: 127.0.0.1
    port: 8164
    append_port: true
  prompt:
    force: false
  generation:
    description: Wakame
    compression_level: -1
    protection: false