# 全局配置文件

# 调试模式开关
# 不支持热重载！
debug: true

# 玩家等级算法
# 不支持热重载！
#
# 可用选项：
# ADVENTURE_LEVEL - AdventureLevel 的等级
# EXPERIENCE_LEVEL - Minecraft 原版经验等级
player_level_provider: EXPERIENCE_LEVEL

# 资源包设置
resource_pack:
  auto_upload:
    enabled: true
    service: self_host
    host: 127.0.0.1
    port: 8164
    append_port: true
  prompt:
    force: false
  generation:
    description: Wakame
    compression_level: -1
    protection: false