# 本战利品表引用了其他战利品表 `example_2`,
# 因此它拥有 `example_2` 所包含的所有样本.
#
# 除此之外, 它还定义了一个 LocalNode.
#
# 因此最终它拥有 `example_c` 中的所有节点:
# - attribute:critical_strike_chance + 1.0
# - attribute:critical_strike_power + 1.0
#
# 以及本地定义的节点:
# - attribute:attack_effect_chance + 0.1
nodes:

  # 这是一个 LocalNode, 其抽取项就在这里定义
  - type: "attribute:attack_effect_chance"
    value: 0.1
    weight: 1
    filters:
      - type: "item:item_level"
        level: "[10,)"

  # 这是一个 CompositeNode, 其抽取项来自战利品表 example_2
  - type: "global:example_2"
